### Write .env.docker
# INFLUXDB_ADMIN_ENABLE=
# INFLUXDB_DB=
# INFLUXDB_USER=
# INFLUXDB_USER_PASSWORD=
# INFLUXDB_ADMIN_USER=
# INFLUXDB_ADMIN_PASSWORD=
# GF_SECURITY_ADMIN_USER=
# GF_SECURITY_ADMIN_PASSWORD=

version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env.docker
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge